USE [master]
GO

/****** Object:  Database [web2text]    Script Date: 07/10/2011 22:12:20 ******/
CREATE DATABASE [web2text] ON  PRIMARY 
( NAME = N'web2text', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\web2text.mdf' , SIZE = 5376KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'web2text_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\web2text_log.LDF' , SIZE = 2112KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [web2text] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [web2text].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [web2text] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [web2text] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [web2text] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [web2text] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [web2text] SET ARITHABORT OFF 
GO

ALTER DATABASE [web2text] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [web2text] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [web2text] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [web2text] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [web2text] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [web2text] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [web2text] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [web2text] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [web2text] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [web2text] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [web2text] SET  ENABLE_BROKER 
GO

ALTER DATABASE [web2text] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [web2text] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [web2text] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [web2text] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [web2text] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [web2text] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [web2text] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [web2text] SET  READ_WRITE 
GO

ALTER DATABASE [web2text] SET RECOVERY FULL 
GO

ALTER DATABASE [web2text] SET  MULTI_USER 
GO

ALTER DATABASE [web2text] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [web2text] SET DB_CHAINING OFF 
GO

